version: '3'

services:
  web:
    platform: linux/x86_64
    build: .
    privileged: true
    # command: /sbin/init #systemctl有効にする場合
    ports:
      - 8083:80
    volumes:
      - .:/var/www/html/
      - ./httpd.conf:/etc/httpd/conf/httpd.conf
      #- ./vhosts.conf:/etc/httpd/conf.d/vhosts.conf #バーチャルホスト利用する際
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
  db:
    image: mysql:5.7
    platform: linux/x86_64
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - 3308:3306
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moneyboard #案件名
      MYSQL_USER: user
      MYSQL_PASSWORD: 1111111
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    ports:
      - 8081:80
    volumes:
      - ./phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini

volumes:
  mysql_data: